FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy pyproject.toml to the work directory
COPY pyproject.toml /app

# Install dependencies
RUN poetry install --only-main

# Copy the rest of the application
COPY . /app

# Command to run the celery worker
CMD ["celery", "-A", "app.celery.app", "--loglevel=INFO"]
